version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - anthaav
  - appspot
  - biryani
  - chekkuthaa
  - chey
  - cheyyavee
  - darbar
  - dengithe
  - Dengutha
  - devara
  - Erri
  - firestore
  - Firestore
  - goldprice
  - gudda
  - Gudu
  - JMNBC
  - kodakaaa
  - kojja
  - Kojja
  - Kojjam
  - Kona
  - lanja
  - Lanja
  - Mastaan
  - Modda
  - mundaa
  - Mundaa
  - mundaaaaaaaaaaaa
  - mundu
  - Pani
  - sessionstorage
  - subcollection
ignoreWords: []
import: []
